{% set version = "0.6.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggwordcloud
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggwordcloud_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggwordcloud/ggwordcloud_{{ version }}.tar.gz
  sha256: f2853304b355c9764079d469ef91c8f9f9ebf311dc0819961a3c76a76706857e

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
    - r-colorspace
    - r-ggplot2 >=3.0.0
    - r-gridtext
    - r-png
    - r-scales >=1.0.0
  run:
    - r-base
    - r-rcpp
    - r-colorspace
    - r-ggplot2 >=3.0.0
    - r-gridtext
    - r-png
    - r-scales >=1.0.0

test:
  commands:
    - $R -e "library('ggwordcloud')"           # [not win]
    - "\"%R%\" -e \"library('ggwordcloud')\""  # [win]

about:
  home: https://github.com/lepennec/ggwordcloud, https://lepennec.github.io/ggwordcloud/
  license: GPL-3.0-only
  summary: Provides a word cloud text geom for 'ggplot2'. Texts are placed so that they do not overlap as in 'ggrepel'.  The algorithm used is a variation around the one of 'wordcloud2.js'.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Type: Package
# Package: ggwordcloud
# Title: A Word Cloud Geom for 'ggplot2'
# Version: 0.5.0
# Authors@R: c(person(given = "Erwan", family = "Le Pennec", role = c("aut", "cre"), email = "lepennec@gmail.com"), person(given = "Kamil", family = "Slowikowski", role = "aut", email = "kslowikowski@gmail.com"))
# Maintainer: Erwan Le Pennec <lepennec@gmail.com>
# Description: Provides a word cloud text geom for 'ggplot2'. Texts are placed so that they do not overlap as in 'ggrepel'.  The algorithm used is a variation around the one of 'wordcloud2.js'.
# License: GPL-3
# Depends: R (>= 2.10), ggplot2 (>= 3.0.0)
# Imports: grid, Rcpp, scales (>= 1.0.0), colorspace, png
# Suggests: testthat (>= 2.0.0), knitr, rmarkdown, ggrepel, wordcloud, wordcloud2, covr, dplyr, tidyr
# LinkingTo: Rcpp
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# URL: https://github.com/lepennec/ggwordcloud, https://lepennec.github.io/ggwordcloud/
# BugReports: https://github.com/lepennec/ggwordcloud/issues
# NeedsCompilation: yes
# Packaged: 2019-06-01 17:55:45 UTC; lepennec
# Author: Erwan Le Pennec [aut, cre], Kamil Slowikowski [aut]
# Repository: CRAN
# Date/Publication: 2019-06-02 04:50:07 UTC
